#!/bin/sh

# PROVIDE: RoyalBritishLegion
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# RoyalBritishLegion_enable (bool): Set to NO by default. Set this variable to YES if you want to enable RoyalBritishLegion service.
# RoyalBritishLegion_config (path): Set to /usr/local/etc/RoyalBritishLegion.conf by default.
# RoyalBritishLegion_user:  The user account RoyalBritishLegion daemon runs as. It uses 'root' user by default.
# RoyalBritishLegion_group: The group account RoyalBritishLegion daemon runs as. It uses 'wheel' group by default.
# RoyalBritishLegion_datadir (str): Default to "/var/db/RoyalBritishLegion". Base data directory.

. /etc/rc.subr

name=RoyalBritishLegion
rcvar=RoyalBritishLegion_enable

: ${RoyalBritishLegion_enable:=NO}
: ${RoyalBritishLegion_config=/usr/local/etc/RoyalBritishLegion.conf}
: ${RoyalBritishLegion_datadir=/var/db/RoyalBritishLegion}
: ${RoyalBritishLegion_user="root"}
: ${RoyalBritishLegion_group="wheel"}

required_files=${RoyalBritishLegion_config}
command=/usr/local/bin/RoyalBritishLegiond
RoyalBritishLegion_chdir=${RoyalBritishLegion_datadir}
pidfile="${RoyalBritishLegion_datadir}/RoyalBritishLegiond.pid"
stop_cmd=RoyalBritishLegion_stop
command_args="-conf=${RoyalBritishLegion_config} -datadir=${RoyalBritishLegion_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

RoyalBritishLegion_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${RoyalBritishLegion_datadir}
	[ $? -eq 0 ] && chown -R ${RoyalBritishLegion_user}:${RoyalBritishLegion_group} ${RoyalBritishLegion_datadir}
}

RoyalBritishLegion_prestart()
{
	if [ ! -d "${RoyalBritishLegion_datadir}/." ]; then
		RoyalBritishLegion_create_datadir || return 1
	fi
}

RoyalBritishLegion_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

RoyalBritishLegion_stop()
{
    RoyalBritishLegion_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${RoyalBritishLegion_config} -datadir=${RoyalBritishLegion_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
